model_name_or_path: Qwen/Qwen2.5-1.5B

stage: sft
do_train: true
finetuning_type: full

dataset: open_thoughts_2_train
eval_dataset: open_thoughts_2_test
template: chatml
cutoff_len: 32768
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: /mnt/checkpoints/isaiah/qwen2.5-1.5B-sft-open_thoughts
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: false
push_to_hub: false

per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

val_size: 0.0
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 1000

report_to: wandb
run_name: qwen_2.5-1.5B
