model_name_or_path: Qwen/Qwen2.5-3B
model_revision: main

stage: sft
do_train: true
finetuning_type: full
deepspeed: configs/deepspeed/ds_z1_config.json

dataset: open_thoughts_2_train
eval_dataset: open_thoughts_2_test
template: chatml
cutoff_len: 32768
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 16

output_dir: /mnt/checkpoints/isaiah/qwen2.5-3B_sft_open-thoughts-2
logging_steps: 2
save_steps: 100
plot_loss: true
overwrite_output_dir: false
push_to_hub: false

per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

val_size: 0.0
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100

report_to: wandb
run_name: qwen2.5-3B
